# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NutrientsCalculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for NutrientsCalculator
  pod 'RealmSwift'

  target 'NutrientsCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'NutrientsCalculatorUITests' do
    # Pods for testing
  end

end
